spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=kitchtestdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
logging.file.name=kitchensink.log
logging.file.path=/Users/marcosordi/Documents/mongodb/kitchensinkh2/kitchensink
# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.xhtml
server.error.whitelabel.enabled=false
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.jboss.as.quickstarts=DEBUG
spring.main.allow-bean-definition-overriding=true
# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html